# Generated by Django 5.0.7 on 2024-10-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_delete_usermodelform'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='user_imag'),
        ),
    ]
