# Generated by Django 5.0.7 on 2024-10-25 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_user_type_property_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property_owner',
            name='user_type',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_type',
        ),
    ]
