# Generated by Django 5.0.7 on 2024-10-26 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_property_owner_user_type_userprofile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_owner',
            name='user_type',
            field=models.CharField(choices=[('regular', 'Regular User'), ('owner', 'Property Owner')], default='owner', max_length=10),
        ),
    ]
