# Generated by Django 5.0.7 on 2024-10-14 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='property_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('area', models.CharField(max_length=50)),
                ('length', models.CharField(max_length=50)),
                ('breadth', models.CharField(max_length=50)),
                ('No_of_floors', models.IntegerField()),
                ('furnished', models.BooleanField(default=True)),
                ('semi_furnished', models.BooleanField(default=True)),
                ('for_family', models.BooleanField(default=True)),
                ('for_business', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='properties_img/')),
                ('post_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property_type')),
            ],
        ),
    ]
