# Generated by Django 5.0.7 on 2024-10-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_owner_property_owners'),
    ]

    operations = [
        migrations.AddField(
            model_name='property_owner',
            name='owner_image',
            field=models.ImageField(blank=True, null=True, upload_to='owner_img/'),
        ),
    ]
