# Generated by Django 5.0.7 on 2024-10-24 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_user_type_property_owner'),
        ('properties', '0004_property_owner_owner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='owners',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.property_owner'),
        ),
        migrations.DeleteModel(
            name='property_owner',
        ),
    ]
