# Generated by Django 5.0.7 on 2024-11-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_property_image1_property_image2_delete_propertyimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AddField(
            model_name='property',
            name='country',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AddField(
            model_name='property',
            name='state',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='No_of_floors',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='for_business',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='for_family',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='semi_furnished',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
