# Generated by Django 5.0.7 on 2024-11-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_property_city_property_country_property_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='state',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
