# Generated by Django 5.0.7 on 2024-12-23 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='county', to='properties.city')),
            ],
        ),
        migrations.CreateModel(
            name='Nearby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nearby_schools', models.JSONField(default=list)),
                ('nearby_hospitals', models.JSONField(default=list)),
                ('nearby_bus_stops', models.JSONField(default=list)),
                ('nearby_police_stations', models.JSONField(default=list)),
                ('nearby_railway', models.JSONField(default=list)),
                ('nearby_gardens', models.JSONField(default=list)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nearby_places', to='properties.county')),
            ],
        ),
    ]
