# Generated by Django 5.0.7 on 2024-11-05 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_alter_property_address_alter_property_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='address',
        ),
        migrations.RemoveField(
            model_name='property',
            name='city',
        ),
        migrations.RemoveField(
            model_name='property',
            name='country',
        ),
        migrations.RemoveField(
            model_name='property',
            name='state',
        ),
    ]
