# Generated by Django 5.0.7 on 2024-12-24 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_county_nearby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nearby',
            name='county',
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='properties.county')),
            ],
        ),
        migrations.AddField(
            model_name='nearby',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nearby_places', to='properties.address'),
        ),
    ]
