# Generated by Django 5.0.7 on 2024-12-24 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_remove_nearby_county_address_nearby_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address',
            new_name='County_id',
        ),
    ]
