# Generated by Django 5.0.7 on 2024-11-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_property_address_property_city_property_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='country',
            field=models.CharField(default='US', max_length=50, null=True),
        ),
    ]
