# Generated by Django 5.0.7 on 2024-12-24 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_rename_address_address_county_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='County_id',
            new_name='County',
        ),
    ]
