# Generated by Django 5.0.7 on 2024-11-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0015_alter_property_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='facing',
            field=models.CharField(blank=True, choices=[('North', 'North'), ('North-East', 'North-East'), ('East', 'East'), ('South-East', 'South-East'), ('South', 'South'), ('South-West', 'South-West'), ('West', 'West'), ('North-West', 'North-West')], default='East', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='garden',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='parking',
            field=models.CharField(blank=True, choices=[('two wheeler', 'two wheeler'), ('car', 'car'), ('No parking', 'No parking')], default='no_parking', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='pet_friendly',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='road_side_parking',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='sunlight_access',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='water_drainage',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
