# Generated by Django 5.0.7 on 2024-12-24 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0015_rename_county_id_address_county'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='County',
            new_name='county',
        ),
    ]
