# Generated by Django 5.0.7 on 2025-01-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0016_rename_county_address_county'),
    ]

    operations = [
        migrations.AddField(
            model_name='nearby',
            name='Air_Pollution_Levels',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
