# Generated by Django 5.0.7 on 2024-11-07 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0017_propertyimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopulationMix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='population_mix',
            field=models.ManyToManyField(blank=True, to='properties.populationmix'),
        ),
        migrations.DeleteModel(
            name='PropertyImage',
        ),
    ]
