# Generated by Django 5.0.7 on 2025-01-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0017_nearby_air_pollution_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='nearby',
            name='Average_Annual_Rainfall',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='nearby',
            name='Business_District_Proximity',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='nearby',
            name='Cell_Network_Coverage',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='nearby',
            name='Commute_Time_to_Downtown',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='nearby',
            name='Cultural_Heritage_Sites',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='nearby',
            name='Earthquake_Zone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='nearby',
            name='Fire_Station_Proximity',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='nearby',
            name='Flood_Zone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='nearby',
            name='Historical_Building_Status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='nearby',
            name='Industrial_Areas',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='nearby',
            name='Internet_Speed',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='nearby',
            name='Major_Highways_Access',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='nearby',
            name='Neighborhood_Crime_Rate',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='nearby',
            name='Noise_Pollution',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='nearby',
            name='Police_Station_Proximity',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='nearby',
            name='Proximity_to_Airport',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='nearby',
            name='Proximity_to_Parks',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='nearby',
            name='Proximity_to_Public_Transit',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='nearby',
            name='Road_Quality',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='nearby',
            name='Snowfall',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
