# Generated by Django 5.0.7 on 2025-01-20 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0019_alter_property_cell_network_coverage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='lift',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='zipcode',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
