# Generated by Django 5.0.7 on 2024-11-07 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0019_remove_property_population_mix_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PopulationMix',
        ),
        migrations.AddField(
            model_name='property',
            name='ENGAGEMENT_CENTERS',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='property',
            name='locality',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='property',
            name='nearby_hospitals',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='nearby_schools',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
