# Generated by Django 5.0.7 on 2025-01-28 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0020_property_lift_property_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.CharField(blank=True, default='No description provided', max_length=200, null=True),
        ),
    ]
