# Generated by Django 5.0.7 on 2024-11-07 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0020_delete_populationmix_property_engagement_centers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='HISTORICAL',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='property',
            name='INDUSTRIES_NEARBY',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='property',
            name='MAINTENANCE',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='property',
            name='UTILITIES',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
