# Generated by Django 5.0.7 on 2024-11-07 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0021_property_historical_property_industries_nearby_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='furnished',
        ),
        migrations.RemoveField(
            model_name='property',
            name='semi_furnished',
        ),
        migrations.AddField(
            model_name='property',
            name='furnish_detail',
            field=models.CharField(blank=True, choices=[('Furnished', 'Furnished'), ('Semi-Furnished', 'Semi-Furnished'), ('Not-Furnished', 'Not-Furnished')], default='Not-Furnished', max_length=100, null=True),
        ),
    ]
