# Generated by Django 5.0.7 on 2024-11-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0022_remove_property_furnished_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='Healthcare',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='property',
            name='Local_Administration',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
