# Generated by Django 5.0.7 on 2024-11-07 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0023_property_healthcare_property_local_administration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='Local_Administration',
            new_name='Administration',
        ),
    ]
