# Generated by Django 5.0.7 on 2024-11-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0024_rename_local_administration_property_administration'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='Environmental_Factors',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='Property_Features',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='Safety_Security',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
