# Generated by Django 5.0.7 on 2024-11-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0025_property_environmental_factors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='Accessibility',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='property',
            name='Education_Child_Care',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='property',
            name='Green_Spaces',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='property',
            name='Weather_Factors',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
