# Generated by Django 5.0.7 on 2024-11-07 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0026_property_accessibility_property_education_child_care_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
