# Generated by Django 5.0.7 on 2024-11-08 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0028_property_posted_date_property_proprty_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='rating_count',
            field=models.IntegerField(default=0),
        ),
    ]
