# Generated by Django 5.0.7 on 2024-11-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0029_property_rating_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='images',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
