# Generated by Django 5.0.7 on 2024-11-10 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0030_property_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='property',
            name='image2',
        ),
    ]
