# Generated by Django 5.0.7 on 2024-11-11 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0033_remove_property_images_property_image1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='Adjacent_Roads',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='Landmark',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='Lifts',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
